const sidebar = {
    showcase: 'Витрина',
    products: 'Продукты',
    categories: 'Категории',
    attributes: 'Атрибуты',
    tags: 'Теги',
    business: 'Бизнес',
    orders: 'Заказы',
    users: 'Пользователи',
    translations: 'Переводы',
    localization: 'Локализация',
    languages: 'Языки',
    currencies: 'Валюты',
    newsletter: 'Рассылки',
    news: 'Новости',
    promotions: 'Акции',
    shop: 'Магазин',
    themes: 'Темы',
    modules: 'Модули',
    settings: 'Настройки',
    importExport: 'Импорт/экспорт',
    import: 'Импорт',
    export: 'Экспорт',
    statistics: 'Статистика',
    additional: 'Дополнительно',
    currentLanguage: 'Язык панели',
    visitShop: 'Посетить магазин',
    logout: 'Выйти',
}

export default sidebar;
