const sidebar = {
    showcase: 'Showcase',
    products: 'Products',
    categories: 'Categories',
    attributes: 'Attributes',
    tags: 'Tags',
    business: 'Business',
    orders: 'Orders',
    users: 'Users',
    translations: 'Translations',
    localization: 'Localization',
    languages: 'Languages',
    currencies: 'Currencies',
    newsletter: 'Newsletter',
    news: 'News',
    promotions: 'Promotions',
    shop: 'Shop',
    themes: 'Themes',
    modules: 'Modules',
    settings: 'Settings',
    importExport: 'Import/Export',
    import: 'Import',
    export: 'Export',
    statistics: 'Statistics',
    additional: 'Additional',
    currentLanguage: 'Admin panel language',
    visitShop: 'Visit shop',
    logout: 'Logout',
}

export default sidebar;
